version: '3' 
#バージョン指定
services:
  view:
  #コマンドを打つときに使う名前
    build: ./
    command: sh -c "yarn dev"
    container_name: 'VIEW'
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true