import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/common/Header'
import Footer from '../components/common/Footer'
import Access from '../components/common/Access'
import Sns from '../components/common/Sns'
import Groups from '../components/common/Groups'
import NextUpdate from '../components/common/NextUpdate'
import TopPage from '../components/common/TopPage'
import Event_info from '../components/common/Event_info'
import Group_info from '../components/common/Group_info'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>第41回技大祭公式ホームページ</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="nutfeslogo_white.png" />
        <link
          rel='stylesheet'
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap"
        />
      </Head>

      <Header/>
      <TopPage/> 
      <Event_info/>
      <Group_info/>
      {/* <Groups/>  */}
      <NextUpdate/>
      <Access/>
      <Sns/>
      <Footer/>
    </>
  )
}

export default Home
