import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/common/Header'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel='stylesheet'
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap"
        />
      </Head>
      <Header/>
      <img src='/logotype.svg'/>
    </>
  )
}

export default Home
