import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/common/Footer'
import Sns from '../components/common/Sns'
import Event_title from '../components/common/Event_title'
import Event_card1 from '../components/common/Event_card1'
import Event_card2 from '../components/common/Event_card2'
import Event_card3 from '../components/common/Event_card3'
import Event_card4 from '../components/common/Event_card4'
import Event_card5 from '../components/common/Event_card5'
import Event_card6 from '../components/common/Event_card6'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>第41回技大祭公式ホームページ</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="nutfeslogo_white.png" />
        <link
          rel='stylesheet'
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap"
        />
      </Head>

      <Event_title/>
      <Event_card1/>
      <Event_card2/>
      <Event_card3/>
      <Event_card4/>
      <Event_card5/>
      <Event_card6/>
      <Sns/>
      <Footer/>
    </>
  )
}

export default Home

