import type { NextPage } from 'next'
import Head from 'next/head'
import Schedule from '../components/common/ScheduleTitle/ScheduleTitle'
import Footer from '../components/common/Footer'
import Sns from '../components/common/Sns'
import Schedule2 from '../components/common/Schedule2'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>第41回技大祭公式ホームページ</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="nutfeslogo_white.png" />
        <link
          rel='stylesheet'
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700&display=swap"
        />
      </Head>
      <Schedule/>
      <Schedule2/>
      <Sns/>
      <Footer/>
    </>
  )
}

export default Home